name: Custom Workflow Secret
on:
   workflow_dispatch:

jobs:
  Saludo_secretos:
    runs-on: ubuntu-latest
    steps:
    - name: Echo de saludo con secreto
      run: echo "${{ secrets.SALUDO }} ${{ secrets.NAME }}, tu contraseña secreta es ${{ secrets.CONTRASENA }}"
